# Commands we definitely don't want to run
# These could seriously mess up someone's computer

# Really bad commands
commands:
  # Don't delete everything
  - "rm -rf /"
  - "rm -rf /*"
  - "rm -rf ~"
  - "rm -rf $HOME"
  - "del /q /s C:\\"
  - "del /q /s %USERPROFILE%"
  - "rmdir /s /q C:\\"
  - "dd if=/dev/zero"
  - "mkfs"
  - "fdisk"
  - "parted"
  - "format"
  - "format C:"
  - "format D:"
  
  # Don't mess with system stuff
  - "sudo rm"
  - "su -"
  - "chmod 777"
  - "chown root"
  - "systemctl stop"
  - "systemctl disable"
  - "service stop"
  - "net stop"
  - "sc stop"
  - "reg delete HKLM"
  - "reg delete HKCU"
  
  # Don't download and run random stuff
  - "curl | bash"
  - "wget | sh"
  - "curl | sh"
  - "bash <(curl"
  - "bash <(wget"
  - "powershell -c \"iex"
  - "powershell iex"
  
  # Don't kill everything
  - "kill -9 -1"
  - "killall -9"
  - "pkill -f"
  - "taskkill /f /im *"
  - "wmic process"

# Patterns that are usually bad news
patterns:
  - "rm\\s+-rf\\s+/"
  - "del\\s+/[qsf]\\s+C:\\\\"
  - "rmdir\\s+/s\\s+/q\\s+C:\\\\"
  - "chmod\\s+777\\s+"
  - "\\|\\s*bash"
  - "\\|\\s*sh"
  - "\\|\\s*powershell"
  - ">/dev/sd[a-z]"
  - "format\\s+[A-Z]:"
  - "del\\s+/[qsf]"
  - "truncate\\s+-s\\s*0"
  - "shred\\s+"
  - "> /dev/null"
  - "> nul"
  - ":(){ :|:& };:"
  - "while true; do"
  - "while\\s*\\(\\s*\\$true\\s*\\)"

# High-risk operations that require explicit confirmation
highRisk:
  - "git reset --hard"
  - "git clean -fd"
  - "docker system prune"
  - "npm ci"
  - "mvn clean"
  - "gradle clean"
  - "pip uninstall"
  - "npm uninstall -g"
  - "brew uninstall"
  - "apt-get remove"
  - "yum remove"
  - "osascript -e"
  - "powershell.exe"
  - "powershell -Command"
  - "powershell -c"
  - "reg delete"
  - "reg add HKLM"
  - "dconf reset"
  - "netsh"
  - "bcdedit"
  - "diskpart"

# Commands that require package manager confirmation
packageManagers:
  - "npm install"
  - "pip install"
  - "brew install"
  - "apt-get install"
  - "yum install"
  - "dnf install"
  - "pacman -S"
  - "choco install"
  - "winget install"
  - "scoop install"

# Desktop control specific patterns
desktopControl:
  # Safe desktop operations
  safe:
    - "open"
    - "start"
    - "xdg-open"
    - "osascript"
    - "wmctrl"
    - "xrandr"
    - "pactl"
    - "amixer"
    - "gsettings"
    - "defaults write"
    - "explorer"
    - "notepad"
    - "calc"
    - "mspaint"
    - "tasklist"
    - "dir"
    - "type"
    - "copy"
    - "move"
    - "mkdir"
    - "echo"
    
  # Medium risk desktop operations
  mediumRisk:
    - "killall"
    - "pkill"
    - "systemctl"
    - "launchctl"
    - "reg add"
    - "dconf write"
    - "taskkill"
    - "net user"
    - "schtasks"
    - "wmic"
    
  # High risk desktop operations  
  highRisk:
    - "sudo killall"
    - "sudo systemctl"
    - "reg delete"
    - "dconf reset"
    - "defaults delete"
    - "taskkill /f"
    - "net stop"
    - "sc delete"
    - "bcdedit"
    - "diskpart"